import React from 'react'

function Privacy() {
  return (
    <>
        <div className='container'>
        <h1 style={{position:"relative",marginTop:"100px",textAlign:"center"}}>Privacy Policy</h1>   
        <h6 style={{marginTop:"20px"}}>At Brownmen, we are committed to protecting the privacy of our website visitors. This Privacy Policy outlines the types of personal information we collect, how we use it, and how we protect it.</h6>
        <h4><b>Personal Information Collection</b></h4>
        <h6 style={{marginTop:"20px"}}>We do not collect any personal information from our website visitors. We do not require you to provide any personal information to access our website.</h6>
        <h4><b>Automated Content Generation</b></h4>
        <h6 style={{marginTop:"20px"}}>Our blog posts related to health of humans are generated by AI. We do not use any personal information to generate these posts.</h6>
        <h4><b>Cookies</b></h4>
        <h6 style={{marginTop:"20px"}}>We do not use cookies on our website.</h6>
        <h4><b>Third-Party Websites</b></h4>
        <h6 style={{marginTop:"20px"}}>Our website may contain links to third-party websites. Please note that these websites have their own privacy policies, and we are not responsible for their policies or practices. We recommend that you review their privacy policies before providing any personal information.</h6>
        <h4><b>Security</b></h4>
        <h6 style={{marginTop:"20px"}}>We take the security of your personal information very seriously. We use industry-standard measures to protect your information from unauthorized access, use, or disclosure.</h6>
        <h4><b>Changes to Privacy Policy</b></h4>
        <h6 style={{marginTop:"20px"}}>We may update this Privacy Policy from time to time. Any changes will be posted on this page.</h6>
        <h4><b>Contact Us</b></h4>
        <h6 style={{marginTop:"20px"}}>If you have any questions or concerns about our Privacy Policy, please contact us at [insert email address].</h6>
       </div>
    </>
 
  )
}
Privacy.requireNavbarAndFooter = true;
export default Privacy