export const yogaTags = [
    "Yoga",
    "YogaPoses",
    "Meditation",
    "YogaLife",
    "HealthyLiving",
    "Wellness",
    "Fitness",
    "Mindfulness",
    "YogaJourney",
    "YogaCommunity",
    "YogaPractice",
    "YogaInspiration",
    "YogaFlow",
    "YogaTeacher",
    "YogaEveryday",
    "StressRelief",
    "Flexibility",
    "Strength",
    "Balance",
    "InnerPeace",
];
export const nutritionTags = [
    "Nutrition",
    "HealthyEating",
    "Diet",
    "NutritionTips",
    "NutritionFacts",
    "BalancedDiet",
    "NutritionAdvice",
    "HealthyDiet",
    "NutritionPlan",
    "EatingWell",
    "NutritionEducation",
    "MealPlanning",
    "NutritionalWellness",
    "WholeFoods",
    "NutritionGoals",
    "Nutritionist",
    "CleanEating",
    "NutritionForLife",
    "HealthyChoices",
    "FoodAsMedicine"
  ];
  
export const fitnessTags = [
    "Fitness",
    "FitnessJourney",
    "Workout",
    "Exercise",
    "HealthyLifestyle",
    "StrengthTraining",
    "Cardio",
    "GymLife",
    "FitLife",
    "FitnessMotivation",
    "FitnessGoals",
    "ActiveLifestyle",
    "HealthAndFitness",
    "Weightlifting",
    "CrossFit",
    "Running",
    "Bodybuilding",
    "Wellness",
    "Nutrition",
    "FitnessCommunity"
  ];
export const healthTags = [
    "Health",
    "HealthyLiving",
    "Wellness",
    "Healthcare",
    "HealthTips",
    "HolisticHealth",
    "MentalHealth",
    "PhysicalHealth",
    "WellBeing",
    "SelfCare",
    "HealthyChoices",
    "MindBodyHealth",
    "HealthAndWellness",
    "HealthyHabits",
    "Nutrition",
    "HealthyMind",
    "HealthyBody",
    "WellnessJourney",
    "FitnessForHealth",
    "HealthyLifestyle"
  ];

  
export const yogaBenefits = [
    "Improved flexibility",
    "Increased strength",
    "Stress reduction",
    "Enhanced mental clarity",
    "Better posture and alignment",
    "Mind-body connection",
    "Relaxation",
    "Inner peace",
    "Weight management",
    "Improved balance",
    "Cardiovascular health",
    "Respiratory health",
    "Pain relief",
    "Flexibility",
    "Muscle tone",
    "Mood enhancement",
    "Better sleep",
    "Digestive health",
    "Energy boost",
    "Spiritual growth"
  ];
  

